import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import classes from '../styles/Home.module.css';
import { Typography, Card, Space } from 'antd';
import { ICity } from '../src/types/interface';
const { Text } = Typography;
//containers
import SearchBar from '../src/containers/SearchBar';
import { usePreferences } from '../src/hooks/usePreference';

const Home: NextPage = () => {
  const [citiSelected, setCitiSelected] = useState<ICity>({
    geonameid: null,
    name: '',
    country: '',
    subcountry: '',
  });
  const { preferences } = usePreferences(citiSelected);
  return (
    <div className={classes.container}>
      <Head>
        <title>Asapp Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <div className={classes.header}>
          <Text type="secondary">Select your favorite city</Text>
          <div>
            {citiSelected.geonameid && (
              <Space>
                <Text>
                  City:<Text strong>{citiSelected.name}</Text>
                </Text>
                -
                <Text>
                  Country: <Text strong>{citiSelected.country}</Text>
                </Text>
              </Space>
            )}
          </div>
        </div>
        <SearchBar
          setCitiSelected={setCitiSelected}
          preferences={preferences}
        />
      </Card>
    </div>
  );
};

export default Home;
