import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import classes from '../styles/Home.module.css';
import { Typography, Card } from 'antd';
import { ICity } from '../src/types/interface';

const { Text } = Typography;
//containers
import SearchBar from 'Containers/SearchBar';

const Home: NextPage = () => {
  const [citiSelected, setCitiSelected] = useState<ICity>({});
  console.log('citiSelected', citiSelected);
  return (
    <div className={classes.container}>
      <Head>
        <title>Asapp Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <div className={classes.header}>
          <Text type="secondary">Select your favorite city</Text>
          {citiSelected.name && (
            <Text>
              City:{citiSelected.name} - Country: {citiSelected.country}
            </Text>
          )}
        </div>
        <SearchBar setCitiSelected={setCitiSelected} />
      </Card>
    </div>
  );
};

export default Home;
